name: Workflow 2
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Read file
        run: echo "The file contains $(cat my-file.txt)"
