name: Workflow 2
on:
  workflow_run:
    workflows: ["Workflow 1"]
    types: [completed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        run: echo "{name}={value}" >> $GITHUB_OUTPUT
