name: Workflow 2
on:
  workflow_run:
    workflows: ["Workflow 1"]
    types: [completed]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "${{ github.event.workflow_run.outputs.my-output }}"
