name: Workflow 1
on:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'compose/**'
      - 'contrib/**'
      - 'dgraphtest/**'
      - 'licenses/**'
      - 'paper/**'
      - 'RFC/**'
      - 'static/**'
      - 't/**'
      - 'telemetry/**'
      - 'wiki/**'
      - '**.dockerignore'
      - '**.gitignore'
      - '**/**.md'
      - '**/**.png'
      - '**/**.sh'
      - '**/**.gif'
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      my-output: ${{ steps.step1.outputs.my-value }}
    steps:
      - name: Save state
        id: step1
        run: echo "action_state=yellow" >> $GITHUB_STATE
