name: Workflow 1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      my-output: ${{ steps.step1.outputs.my-value }}
    steps:
      - name: Save state
        id: step1
        run: echo "{name}={Hello world}" >> $GITHUB_STATE
