name: Workflow 1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      my-output: ${{ steps.step1.outputs.my-value }}
    steps:
      - name: Step 1
        id: step1
        run: echo "::set-output name=my-value::hello world"
