name: Workflow 1
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "::set-env name=MY_VAR::hello world"
      - name: Step 2
        run: echo "MY_VAR=$MY_VAR"
  